name: "Static Analyze"

on:
  pull_request:
  push:
    branches:
      - "1.x"
  schedule:
    - cron:  '* 8 * * *'

jobs:
  compatibility:
    name: "Static Analyze"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Test Compatibility"
        run: "composer static:analyze"