name: Tests

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '15 8 * * *'

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependecies through composer
        run: composer install
      - name: Run testsuite
        run: composer test

